# Generated by Django 5.1.6 on 2025-03-14 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_reference_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curriculumvitae',
            old_name='degree',
            new_name='degrees',
        ),
        migrations.RenameField(
            model_name='curriculumvitae',
            old_name='experience',
            new_name='experiences',
        ),
        migrations.RenameField(
            model_name='curriculumvitae',
            old_name='skill',
            new_name='skills',
        ),
    ]
