# Generated by Django 5.1.6 on 2025-03-31 03:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_degree_entity_alter_degree_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Degree',
            new_name='Education',
        ),
        migrations.RenameField(
            model_name='curriculumvitae',
            old_name='degrees',
            new_name='educations',
        ),
    ]
