# Generated by Django 5.1.6 on 2025-04-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_alter_skill_expertise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='phone',
            field=models.CharField(help_text='Just numbers, not spaces or special characters', max_length=30),
        ),
    ]
