# Generated by Django 5.1.6 on 2025-04-02 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_alter_reference_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDemographic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='media/user/avatars')),
                ('adress', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=30)),
                ('profession', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('FREELANCER', 'FREELANCER'), ('EMPLOYED', 'EMPLOYED'), ('OPEN TO  WORK', 'OPEN TO  WORK'), ('OPEN TO INTERVIEWS', 'OPEN TO INTERVIEWS')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('LinkedIn', 'LinkedIn'), ('x/Twitter', 'x/Twitter'), ('Facebook', 'facebook'), ('Portfolio', 'portfolio')], max_length=20)),
                ('url', models.URLField()),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_socials', to='manager.userdemographic')),
            ],
        ),
        migrations.DeleteModel(
            name='ProfileUser',
        ),
    ]
