# Generated by Django 5.1.6 on 2025-04-02 22:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_userdemographic_socialmedia_delete_profileuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdemographic',
            name='adress',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3, 'The content is too short')]),
        ),
        migrations.AlterField(
            model_name='userdemographic',
            name='profession',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3, 'The content is too short')]),
        ),
    ]
